### ISSUE TITLE
Bug: 배포 서버에서 API 호출 시 응답 데이터의 시간값에 9가 더해지는 문제

### ISSUE THREAD

**Issue by Wo-ogie** [HealthperDevelopers/Server_Healthper#31]
다음과 같이 데이터가 저장되어 있는 상황에서 API 호출 시 응답 데이터에 시간값이 이상한 현상 발견.
![image](https://user-images.githubusercontent.com/60748900/186577915-a6e45a64-63c0-4ce4-8cfd-456d960da69e.png)

**API 호출 - `서버주소/post/487`**
```json
{
    "postId": 487,
    "postType": "NORMAL",
    "writer": {
        "memberId": 480,
        "nickName": "Woogie",
        "status": "NORMAL"
    },
    "title": "제목5",
    "content": "테스트를 위한 5번 게시글",
    "postStatus": "NORMAL",
    "createdAt": "2022-08-25T22:30:22.447814",
    "comments": []
}
```
API 응답 시 시간값이 9가 더해져서 반환된다.

**Comment by Wo-ogie** [comment]
Local 환경과 EC2 Instance에 Spring 서버를 올려서 똑같이 테스트 해보았을때 해당 문제를 확인할 수 없었음. 정상 동작
-> Elastic Beanstalk 쪽 문제가 아닐까 추정됨

**Comment by peterysh** [comment]
fix: #31 배포한 elastic beanstalk과 연결된 ec2의 서버 시각을 한국 시각으로 바꾸어서 해결.

현재 시각 확인
[root@localhost ~] date
Tue Aug 24 04:40:30 UTC 2021

시스템 전역 timezone은 /etc/sysconfig/clock 에 정의, 한국 기준으로 재설정하자.
vim /etc/sysconfig/clock

===============
수정 전
ZONE="UTC"
UTC=true

수정 후
ZONE="Asia/Seoul"
KST=True

===============

/etc/localtime 내용 확인 -> UTC로 내용 구성이 되어있음
[root@localhost ~] cat /etc/localtime
TZif2UTCTZif2 
UTC0

기존(UTC 시간) /etc/localtime 삭제
[root@localhost ~] rm /etc/localtime

한국 표준시간대 정보를 심볼릭 링크 설정
[root@localhost ~] ln -s /usr/share/zoneinfo/Asia/Seoul /etc/localtime

변경사항 확인
[root@localhost ~] date
Tue Aug 24 13:43:32 KST 2021
